[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true

[project]
name = "apiana-ai"
dynamic = ["version"]
description = "Apiana AI: Self reflective AI companion."
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "neo4j>=5.28.1",
    "neo4j-graphrag>=1.7.0",
    "numpy>=2.2.6",
    "openai>=1.82.1",
    "textual>=3.2.0",
    "torch>=2.7.0",
    "transformers>=4.52.4",
]

[project.scripts]
gpt-export-tui = "apiana.applications.chatgpt_export_tui.tui:main"


[tool.uv.sources]
apiana = { workspace = true }


[tool.hatch.build.targets.wheel]
packages = ["apiana"]

[tool.hatch.build]
packages = ["apiana"]
include = [

    "LICENSE",
    "README.md"
]

[dependency-groups]
dev = [
    "ruff>=0.11.7",
    "hatch>=1.14.1",
    "textual-dev>=1.7.0",
    "debugpy>=1.8.14",
]
