# Local Development Configuration
# Everything runs on the local machine with no external dependencies

[general]
environment = "local"
batch_size = 10
output_base_dir = "output"

[prompt]
name = "default"
system_prompt_file = "prompts/self-reflective-system-message.txt"
user_prompt_template_file = "prompts/self-reflective-prompt-template.txt"

[llm_provider]
# Local Ollama instance
model = "llama3.2"
base_url = "http://localhost:11434/v1"
api_key = "ollama"
temperature = 0.7
max_tokens = 4096

[embedder]
# Local embeddings using Transformers
type = "local"
model = "nomic-ai/nomic-embed-text-v1"
dimension = 768

[neo4j]
# Local Neo4j instance
uri = "bolt://localhost:7687"
username = "neo4j"
password = "password"
# database = "neo4j"  # Optional: defaults to the default database