# Production Configuration
# Uses 3rd party APIs and hosted services

[general]
environment = "production"
batch_size = 50
output_base_dir = "output"

[prompt]
name = "default"
system_prompt_file = "prompts/self-reflective-system-message.txt"
user_prompt_template_file = "prompts/self-reflective-prompt-template.txt"

[llm_provider]
# OpenAI API
model = "gpt-4o-mini"
base_url = "https://api.openai.com/v1"
api_key = "${OPENAI_API_KEY}"  # Environment variable
temperature = 0.7
max_tokens = 4096

[embedder]
# OpenAI embeddings (or could use local for privacy)
type = "openai"
model = "text-embedding-3-small"
dimension = 1536
# For OpenAI embeddings, api_key will be read from llm_provider

[neo4j]
# Hosted Neo4j instance (e.g., Neo4j Aura)
uri = "${NEO4J_URI}"  # Environment variable
username = "${NEO4J_USERNAME}"  # Environment variable
password = "${NEO4J_PASSWORD}"  # Environment variable
database = "neo4j"